### ISSUE TITLE
Tier 3+4 dont recognize previous recipe's in refined storage autocrafting

### ISSUE THREAD

**Issue by Zalandrius** [Christofmeg/MoreIndustrialForegoingAddons#1]
As you can see I have all recipe's in my crafter in the dissolution chamber, but once you start the craft it doesn't recognize the previous recipe in the crafter. Is this a bug or am I doing something wrong? This is game version 1.20.1

![crafter](https://github.com/user-attachments/assets/a083f6a8-9c51-4525-b2c5-80f32aeaed2d)
![autocrafting menu](https://github.com/user-attachments/assets/56a12563-beec-4d73-a6ba-bcf5e3f8d47f)
![crafter manager](https://github.com/user-attachments/assets/510a1393-d089-4dd3-a47e-0db5c0e3be22)

**Comment by Christofmeg** [comment]
I'll be looking into this

**Comment by Christofmeg** [comment]
It will be fixed once my [pull request](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/1461) gets merged into Industrial-Foregoing

**Comment by Zalandrius** [comment]
You are amazing! Thank you! Good luck in the modding community.
